spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/planora
spring.datasource.username=planora_app
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
